version: '3.9'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 0000
      POSTGRES_DB: product_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fastapi:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://postgres:0000@db:5432/product_db

  mcp:
    build: .
    command: python mcp_server.py
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      DATABASE_URL : postgresql://postgres:0000@localhost:5432/product_db


volumes:
  pgdata:
